### PR TITLE
weekly: completing pending tasks

### PR DESCRIPTION
**Pull request by sebastianjnuwu**
The purpose of this PR is to resolve all pending issues before starting the development of other commands, and also to adjust the aesthetics of the bot in addition to adding documentation.

### CODE REVIEW

**Review by sebastianjnuwu — COMMENTED** [review]
Removing the Spanish language plus adding some supplementary settings, apparently no errors in sight

**Review by rehhbeka — COMMENTED** [review]
The settings are correct, but the most important things still need to be done, especially in terms of aesthetics, okay?

**Review by rehhbeka — COMMENTED** [review]
didn't you see this in the first commit? Watch!

**Review by rehhbeka — COMMENTED** [review]
Dependencies must first go through the "canary version"

**Comment by sebastianjnuwu** [comment]
how am i going to test this? the hosting is already at the limit!? replit 🤡

**Review by sebastianjnuwu — COMMENTED** [review]
I think for this to work, you have to configure it not to delete the branch after approving the PR

**Comment by sebastianjnuwu** [comment]
in reality the bot is for our use, not for the public, in fact it is for the public to use

**Review by sebastianjnuwu — COMMENTED** [review]
the vscode or I at least don't know how to set the folder settings...

**Review by sebastianjnuwu — COMMENTED** [review]
What is this lol

**Review by sebastianjnuwu — COMMENTED** [review]
vscode is boring on mobile

**Comment by sebastianjnuwu** [comment]
damn there was an error apparently

**Review by sebastianjnuwu — COMMENTED** [review]
Need husky is needed to run precommands and automate git

**Review by sebastianjnuwu — COMMENTED** [review]
there is still a bug, it will temporarily look like this

**Comment by sebastianjnuwu** [comment]
Test for me cell phone is dying

**Review by sebastianjnuwu — COMMENTED** [review]
Lol

**Pull request merged**
